config/routes.rb
Rails.application.routes.draw do
  root to: 'ships#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :ships, only: [:new, :create, :show, :edit] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  namespace :owner do
    resources :ships, only: [:index]
    resources :bookings, only: [:index] do
      member do
        patch "accept"
        patch "decline"
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :ship
  belongs_to :user

  def set_total_price!
    self.total_price = (end_date - start_date).to_f * ship.price_per_day
    self.total_price += 50.0 if captain?
  end

  validates :status, presence: true, inclusion: { in: ["pending", "confirmed", "canceled"], allow_nil: false }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
  validates :number_of_guests, presence: true
end

app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  validates :model, presence: true
  validates :address, presence: true
  validates :photo, presence: true
  validates :price_per_day, presence: true
  validates :capacity_max, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ships, dependent: :destroy, foreign_key: :owner_id # => OWNER
  has_many :bookings # => RENTER

  has_many :owner_bookings, through: :ships, source: :bookings # => OWNER
  # has_many :booked_ships, through: :bookings # => RENTER

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio, :avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @ship = Ship.find(params[:ship_id])
    @booking = Booking.new
  end

  def create
    @ship = Ship.find(params[:ship_id])
    @booking = Booking.new(booking_params)
    @booking.ship = @ship
    @booking.user = current_user
    @booking.set_total_price!

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def index
    @bookings = current_user.bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :number_of_guests, :captain, :avatar)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :decline]

  def index
    @bookings = Booking.joins(:ship).where(ships: { owner: current_user })
  end

  def accept
    @booking.status = "confirmed"
    @booking.save
    redirect_to owner_bookings_path
  end

  def decline
    @booking.status = "canceled"
    @booking.save
    redirect_to owner_bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  # def booking_params
  #   params.require(:booking).permit(:start_date, :end_date, :number_of_guests, :captain)
  # end
end

app/controllers/owner/ships_controller.rb
class Owner::ShipsController < ApplicationController
  def index
    @ships = current_user.ships
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/ships_controller.rb
# frozen_string_literal: true

class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @ships = Ship.where.not(owner: current_user)
  end

  def show
    @booking = Booking.new
    @bookings = @ship.bookings
    @ship = Ship.find(params[:id])
    @alert_message = "You are viewing the ship of #{@ship.owner.first_name}"

    @markers = [{
      lat: @ship.latitude,
      lng: @ship.longitude
    }]
  end

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)
    @ship.owner = current_user
    if @ship.save
      redirect_to ship_path(@ship)
    else
      render :new
    end
  end

  def edit
  end

  private

  def ship_params
    params.require(:ship).permit(:captain, :address, :model, :photo, :price_per_day, :description, :photo, :capacity_max)
  end

  def set_ship
    @ship = Ship.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def booking_status_class(booking)
    booking.status == 'confirmed' ? 'text-success' : 'text-danger'
  end
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="pt-3">
    <% if @bookings.empty? %>
        <h3>You have booked any ships yet</h3>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="card-product position-relative">
          <%= cl_image_tag booking.ship.photo, height: 100, width: 150, crop: :fill %>
          <h2 class="model-name"><%= booking.ship.model %></h2>
          <div class="card-product-infos">
            <div class="user-infos d-flex justify-content-center align-items-center mb-2">
              <%= cl_image_tag booking.ship.owner.avatar, height: 50, width: 50, gravity: :face, class: 'booking-user-avatar' %>
              <p class="ml-2 mt-0">
                <%= booking.ship.owner.first_name %> <%= booking.ship.owner.last_name %>
                <% if booking.number_of_guests > 0 %>
                  <br>
                  <span> and <%= booking.number_of_guests %> more.</span>
                <% end %>
                </p>
            </div>
            <% if !booking.captain %>
              <p class="pl-5 text-danger"><strong>A captain is needed</strong></p>
            <% else %>
              <p class="pl-5 font-weight-lighter font-italic"><small>No need for captain</small></p>
            <% end %>
          </div>
          <div class="card-product-dates-and-price">
            <p>
              <span class="font-weight-lighter">from</span>
              <strong class="mx-1"><%= booking.start_date.strftime("%d/%m/%y") %></strong>
              <span class="font-weight-lighter">to</span>
              <strong class="mx-1"><%= booking.end_date.strftime("%d/%m/%y") %></strong>
            </p>
            <p>
              <span class="font-weight-lighter">for</span>
              <strong class="total_price"><%= booking.total_price %></strong>
              <i class="fab fa-galactic-republic"></i>
            </p>
          </div>
          <div class="card-product-status-infos">
            <p class="m-0 <%= booking_status_class(booking) %>"><%= booking.status %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class= "container">
  <div class= "third-container">
    <div class= "form-grey">
      <div class=" text-center col-12 col-md-8 offset-md-2">
          <h2>You're booking the</h2>
          <h1><%= @ship.model %></h1><br>

          <%= simple_form_for [@ship, @booking] do |f| %>
            <p><%= f.input :start_date, label: 'When your journey will start?' %></p>

            <p><%= f.input :end_date, label: 'When your journey will end?' %></p>

            <p><%= f.input :number_of_guests, placeholder: "How many guests will you have?" %></p>

            <p class="custom-control custom-switch">
              <%#= f.input :captain, input: { class: 'custom-control-input' }, wrapper_html: { class: 'custom-control custom-switch'}, label: false %>
              <input type="checkbox" class="custom-control-input" id="booking_captain" name="booking[captain]">
              <label class="custom-control-label" for="booking_captain">Do you want to travel with a captain? (+50)</label>
            </p>

            <br>

             <!--  <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="customSwitch1">
              </div> -->

            <div class="text-center">
              <%= f.button :submit, "Book this ship", class: "btn btn-ghost"%>
            </div>
          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Righteous|Varela+Round&display=swap" rel="stylesheet" type="text/css"/>
    <link href="//db.onlinewebfonts.com/c/dcb5cf864bdbede594c7d31a204dee8d?family=Star+Jedi+Hollow" rel="stylesheet" type="text/css"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>STARTOUR</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="container">
  <div class="pt-3">
    <% if @bookings.empty? %>
        <h3>Noone has booked your ships</h3>
    <% else %>
      <% @bookings.each do |booking| %>
        <div class="card-product position-relative">
          <%= cl_image_tag booking.ship.photo, height: 100, width: 150, crop: :fill %>
          <h2 class="model-name"><%= booking.ship.model %></h2>
          <div class="card-product-infos">
            <div class="user-infos d-flex justify-content-center align-items-center mb-2">
              <%= cl_image_tag booking.user.avatar, height: 50, width: 50, gravity: :face, class: 'booking-user-avatar' %>
              <p class="ml-2 mt-0">
                <%= booking.user.first_name %> <%= booking.user.last_name %>
                <% if booking.number_of_guests > 0 %>
                  <br>
                  <span> and <%= booking.number_of_guests %> more.</span>
                <% end %>
                </p>
            </div>
            <% if !booking.captain %>
              <p class="pl-5 text-danger"><strong>A captain is needed</strong></p>
            <% else %>
              <p class="pl-5 font-weight-lighter font-italic"><small>No need for captain</small></p>
            <% end %>
          </div>
          <div class="card-product-dates-and-price">
            <p>
              <span class="font-weight-lighter">from</span>
              <strong class="mx-1"><%= booking.start_date.strftime("%d/%m/%y") %></strong>
              <span class="font-weight-lighter">to</span>
              <strong class="mx-1"><%= booking.end_date.strftime("%d/%m/%y") %></strong>
            </p>
            <p>
              <span class="font-weight-lighter">for</span>
              <strong class="total_price"><%= booking.total_price %></strong>
              <i class="fab fa-galactic-republic"></i>
            </p>
          </div>
          <div class="card-product-status-infos">
            <% if booking.status == "pending" %>
              <%= link_to 'accept', accept_owner_booking_path(booking),
                                    method: :patch,
                                    class: "btn btn-ghost-owner mb-3 btn-accept" %>
              <%= link_to 'decline', decline_owner_booking_path(booking),
                                     method: :patch,
                                     class: "btn btn-ghost-owner" %>
            <% else %>
              <p class="m-0 <%= booking_status_class(booking) %>"><%= booking.status %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/owner/ships/index.html.erb
<div class="container">
  <div class= "title-my-ships">
    <h1>My galactic garage</h1>
  </div>
  <div class="row">
    <% @ships.each do |ship| %>
      <div class="col-12 col-md-6 col-lg-3">
        <%= link_to ship_path(ship) do %>
          <div class="card-trip link-card-trip">
            <%= cl_image_tag ship.photo, height: 300, width: 400, crop: :fill %>
            <div class="card-trip-infos-myships">
                <h2><%= ship.model %></h2>
              <div class="card-trip-pricing-myships">
                <p><%= ship.price_per_day %> <i class="fab fa-galactic-republic"></i></p>
              </div>
<!--               <%#= image_tag ship.owner.avatar.url(:bright_face), height: 40, width: 40, crop: :fill, class: "card-trip-user avatar-bordered" %> -->
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to "Add a new ship", new_ship_path, class: "btn btn-ghost" %>
</div>

app/views/pages/home3.html.erb
<style>
@import url(http://fonts.googleapis.com/css?family=Droid+Sans:400,700);

* { padding: 0; margin: 0; }

body, html
{
  width: 100%;
  height: 100%;
  font-family: "Droid Sans", arial, verdana, sans-serif;
  font-weight: 700;
  color: #ff6;
  background-color: #000;
  overflow: hidden;
}

p#start
{
  position: relative;
  width: 16em;
  font-size: 200%;
  font-weight: 500;
  margin: 20% auto;
  color: #4ee;
  opacity: 0;
  z-index: 1;
  -webkit-animation: intro 3s ease-out;
  -moz-animation: intro 3s ease-out;
  -ms-animation: intro 3s ease-out;
  -o-animation: intro 3s ease-out;
  animation: intro 3s ease-out;
}

@-webkit-keyframes intro {
  0% { opacity: 1; }
  90% { opacity: 1; }
  100% { opacity: 0; }
}

@-moz-keyframes intro {
  0% { opacity: 1; }
  90% { opacity: 1; }
  100% { opacity: 0; }
}

@-ms-keyframes intro {
  0% { opacity: 1; }
  90% { opacity: 1; }
  100% { opacity: 0; }
}

@-o-keyframes intro {
  0% { opacity: 1; }
  90% { opacity: 1; }
  100% { opacity: 0; }
}

@keyframes intro {
  0% { opacity: 1; }
  90% { opacity: 1; }
  100% { opacity: 0; }
}

h1
{
  position: absolute;
  width: 2.6em;
  left: 50%;
  top: 25%;
  font-size: 10em;
  text-align: center;
  margin-left: -1.3em;
  line-height: 0.8em;
  letter-spacing: -0.05em;
  color: #000;
  text-shadow: -2px -2px 0 #ff6, 2px -2px 0 #ff6, -2px 2px 0 #ff6, 2px 2px 0 #ff6;
  opacity: 0;
  z-index: 1;
  -webkit-animation: logo 5s ease-out 2.5s;
  -moz-animation: logo 5s ease-out 2.5s;
  -ms-animation: logo 5s ease-out 2.5s;
  -o-animation: logo 5s ease-out 2.5s;
  animation: logo 5s ease-out 2.5s;
}

h1 sub
{
  display: block;
  font-size: 0.3em;
  letter-spacing: 0;
  line-height: 0.8em;
}

@-webkit-keyframes logo {
  0% { -webkit-transform: scale(1); opacity: 1; }
  50% { opacity: 1; }
  100% { -webkit-transform: scale(0.1); opacity: 0; }
}

@-moz-keyframes logo {
  0% { -moz-transform: scale(1); opacity: 1; }
  50% { opacity: 1; }
  100% { -moz-transform: scale(0.1); opacity: 0; }
}

@-ms-keyframes logo {
  0% { -ms-transform: scale(1); opacity: 1; }
  50% { opacity: 1; }
  100% { -ms-transform: scale(0.1); opacity: 0; }
}

@-o-keyframes logo {
  0% { -o-transform: scale(1); opacity: 1; }
  50% { opacity: 1; }
  100% { -o-transform: scale(0.1); opacity: 0; }
}

@keyframes logo {
  0% { transform: scale(1); opacity: 1; }
  50% { opacity: 1; }
  100% { transform: scale(0.1); opacity: 0; }
}

/* the interesting 3D scrolling stuff */
#titles
{
  position: absolute;
  width: 18em;
  height: 50em;
  bottom: 0;
  left: 50%;
  margin-left: -9em;
  font-size: 350%;
  text-align: justify;
  overflow: hidden;
  -webkit-transform-origin: 50% 100%;
  -moz-transform-origin: 50% 100%;
  -ms-transform-origin: 50% 100%;
  -o-transform-origin: 50% 100%;
  transform-origin: 50% 100%;
  -webkit-transform: perspective(300px) rotateX(25deg);
  -moz-transform: perspective(300px) rotateX(25deg);
  -ms-transform: perspective(300px) rotateX(25deg);
  -o-transform: perspective(300px) rotateX(25deg);
  transform: perspective(300px) rotateX(25deg);
}

#titles:after
{
  position: absolute;
  content: ' ';
  left: 0;
  right: 0;
  top: 0;
  bottom: 60%;
  background-image: -webkit-linear-gradient(top, rgba(0,0,0,1) 0%, transparent 100%);
  background-image: -moz-linear-gradient(top, rgba(0,0,0,1) 0%, transparent 100%);
  background-image: -ms-linear-gradient(top, rgba(0,0,0,1) 0%, transparent 100%);
  background-image: -o-linear-gradient(top, rgba(0,0,0,1) 0%, transparent 100%);
  background-image: linear-gradient(top, rgba(0,0,0,1) 0%, transparent 100%);
  pointer-events: none;
}

#titles p
{
  text-align: justify;
  margin: 0.8em 0;
}

#titles p.center
{
  text-align: center;
}

#titles a
{
  color: #ff6;
  text-decoration: underline;
}

#titlecontent
{
  position: absolute;
  top: 100%;
  -webkit-animation: scroll 100s linear 4s infinite;
  -moz-animation: scroll 100s linear 4s infinite;
  -ms-animation: scroll 100s linear 4s infinite;
  -o-animation: scroll 100s linear 4s infinite;
  animation: scroll 100s linear 4s infinite;
}

/* animation */
@-webkit-keyframes scroll {
  0% { top: 100%; }
  100% { top: -170%; }
}

@-moz-keyframes scroll {
  0% { top: 100%; }
  100% { top: -170%; }
}

@-ms-keyframes scroll {
  0% { top: 100%; }
  100% { top: -170%; }
}

@-o-keyframes scroll {
  0% { top: 100%; }
  100% { top: -170%; }
}

@keyframes scroll {
  0% { top: 100%; }
  100% { top: -170%; }
}
</style>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://www.movie-object-reproduction.com/Files/17627/Img/07/CasqueLukeSkywalkerPilotRebelHelmet308-zoom.jpg" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="banner" style="">
  <div class="banner-content">
    <h1></h1>
    <body cz-shortcut-listen="true">

<p id="start">Il y a peu de temps, dans un navigateur très, très proche....
des developpeurs du wagon</p>


<div id="titles"><div id="titlecontent">

  <p class="center">EPISODE 314<br>ALL YOU NEED IS CODE</p>
  <p>STAR TOUR</p>

  <p>C'est une période de guerre pour des vendeurs.</p>

  <p>Il s'agit d'un style Star Wars qui fait défiler les titres 3D en CSS3. Il est possible qu'il n'ait aucun but pratique, mais il a l'air génial \o/</p>

  <p>Avant que les cinéphiles ne se mettent à fulminer, je me rends compte que Star Wars n'a pas été le premier à utiliser des titres 3D rampants, mais peu d'entre vous se souviendront de la série Flash Gordon ou de l'adaptation en 1936 de "Things to Come" de HG Wells.</p>

  <p>Aussi, en mentionnant "Star Wars", tout le monde comprendra ce que je veux dire. Et je recevrai plusieurs milliers de visites supplémentaires.
  donc plus de location de vaisseau.</p>

  <p>Les titres déroulants fonctionnent bien dans Chrome, Safari et Firefox. Opera n'implémente pas encore de transformations 3D, mais le texte défilera. Les utilisateurs d'IE reçoivent une page blanche. C'est dommage, mais IE10 devrait le supporter...
  un jour....</p>

  <p>Tout le code est contenu dans ce fichier HTML unique.........
Je sais que c'est mal.........
mais c'est un exercice alors on test tout \o/

  </p><p class="center">Regarde le code source, Luke !</p>

  <p>Désolée. Je n'ai pas pu résister.</p>

  <p class="center"><a href="http://www.lewagon.com/">lewagon.com/<br></a></p>

  <p>allez sur github <a href="http://github.com/esbo22">@esbo22</a> – J'adorerais voir comment vous utilisez à votre tour !</p>

  <p>Enfin, les films originaux, non falsifiés, restent les meilleurs. Arrête de les tripoter !</p>

</div></div>


</body>
    <a class="btn btn-flat" href="#">Insciption</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @ships.each do |ship| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'starwars.jpg' %>');">
          <div class="card-description">
            <h2><%= ship.model %></h2>
          </div>
          <%= link_to "", ship_path(ship), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<br>
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/yropert/startour" target="_blank"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    I <i class="fas fa-heart"></i> Galaxy
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All ships", root_path, class: "btn btn-dark" %>
          <%= link_to "My bookings", owner_bookings_path, class: "btn btn-dark" %>
          <%= link_to "My own request", bookings_path, class: "btn btn-dark" %>
          <%= link_to "My ships", owner_ships_path, class: "btn btn-dark mr-3" %>
        </li>

        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar, gravity: :face, height: 50, width: 50, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link nav-text" %>
        </li>
          <%= link_to "Sign up", "/users/sign_up", class: "nav-link nav-text" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/ships/_editform.html.erb
<div class="container">
  <div class="form-grey">
    <h3><%= current_user.first_name %>, update your ship</h3>

    <%= simple_form_for [@owner, @ship] do |f| %>
      <!--   <%#= f.association :model, collection: ["ARC170", "CR90", "Falcon Millenium", "N1 Starfighter", "Quadjumper", "T70", "T-4a Lambda", "T-47 Speeder", "Tie Fighter", "Tie Interceptor", "X-Wing" ] %> -->
      <%= f.input :model %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.input :address %>
      <%= f.input :captain %>
      <%= f.input :price_per_day %>
      <%= f.input :capacity_max %>
      <%= f.input :description %>

      <%= f.button :submit, "Update your ship", class: "btn btn-ghost" %>
    <% end %>
    <br>
  </div>
</div>

app/views/ships/edit.html.erb
<h1>Editing <%= @ship.model %></h1><br>

<%= render 'editform', ship: @ship %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', owner_ships_path %>

app/views/ships/new.html.erb
<%= render 'form' %>

app/views/ships/show.html.erb
<div class="banner-show-ship" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @ship.photo %>);">
  <div class="banner-show-ship-name">
    <h1><%= @ship.model %></h1>
  </div>

</div>

<div class="container">
  <div class="row">
      <div class="col-12 col-lg-6">
        <div class="card-ship-form-grey p-3">
          <p><strong>Owner</strong>: <%= @ship.owner.first_name + ' ' + @ship.owner.last_name %></p>
          <p><strong><%= @ship.price_per_day %> </strong> <i class="fab fa-galactic-republic"> /day</i> </p>
          <p> <i class="fas fa-users"></i> <%= @ship.capacity_max %></i></p>
          <p><%= @ship.description %></p>
          <p><i class="fas fa-map-marker-alt"></i> <%= @ship.address %></p>
          <div class="card-ship-button">
            <%= link_to "Book this ship", new_ship_booking_path(@ship), class: "btn btn-ghost" %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6">
        <div class="p-3">
          <div
            id="map"
            style="width: 100%;
            height: 375px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- <div class="card-ship-button">
  <%= link_to "Book this ship", new_ship_booking_path(@ship), class: "btn btn-ghost" %>
</div> -->